--Alterado
CREATE TABLE TB_PRODUTO (
ID_PRODUTO BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) CONSTRAINT PK_PRODUTO PRIMARY KEY, 
NM_PRODUTO VARCHAR(100) NOT NULL,
NM_MARCA VARCHAR(50) NOT NULL,
GN_PRODUTO VARCHAR(100) NOT NULL,
DS_PRODUTO VARCHAR(1000) NOT NULL,
TM_PRODUTO VARCHAR(50) NOT NULL,
COR_PRODUTO VARCHAR(50) NOT NULL,
DT_CADASTRO TIMESTAMP NOT NULL,
VL_PRODUTO DECIMAL(12,2) NOT NULL,
QTD_ATUAL INTEGER NOT NULL
--ID_CATEGORIA BIGINT NOT NULL
);

--Alterado
--CREATE TABLE TB_MARCA(
--ID_MARCA BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) CONSTRAINT PK_MARCA PRIMARY KEY,
--NOME_MARCA VARCHAR(100) NOT NULL
--);

CREATE TABLE TB_CATEGORIA (
ID_CATEGORIA BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) CONSTRAINT PK_CATEGORIA PRIMARY KEY,
NM_CATEGORIA VARCHAR(100) NOT NULL
);
--ALTER TABLE TB_PRODUTO ADD CONSTRAINT FK_PRODUTO_MARCA FOREIGN KEY (ID_MARCA) REFERENCES TB_MARCA(ID_MARCA);
--ALTER TABLE TB_PRODUTO ADD CONSTRAINT FK_PRODUTO_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES TB_CATEGORIA(ID_CATEGORIA);

---Avaliar
CREATE TABLE TB_PRODUTO_CATEGORIA (
ID_PRODUTO BIGINT NOT NULL,
ID_CATEGORIA BIGINT NOT NULL
);

ALTER TABLE TB_PRODUTO_CATEGORIA ADD CONSTRAINT FK_PRODUTO_CATEGORIA FOREIGN KEY (ID_PRODUTO) REFERENCES TB_PRODUTO(ID_PRODUTO);
ALTER TABLE TB_PRODUTO_CATEGORIA ADD CONSTRAINT FK_CATEGORIA_PRODUTO FOREIGN KEY (ID_CATEGORIA) REFERENCES TB_CATEGORIA(ID_CATEGORIA);
---*/

CREATE TABLE TB_IMAGEM (
ID_IMAGEM BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) CONSTRAINT PK_IMAGEM PRIMARY KEY,
NM_IMAGEM VARCHAR(100) NOT NULL,
DS_IMAGEM VARCHAR(100),
ID_PRODUTO BIGINT NOT NULL
);

ALTER TABLE TB_IMAGEM ADD CONSTRAINT FK_PRODUTO_IMAGEM FOREIGN KEY (ID_PRODUTO) REFERENCES TB_PRODUTO(ID_PRODUTO);





--ACRESCENTADO
/*CREATE TABLE USUARIO_CLIENTE(
ID_CLIENTE BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) CONSTRAINT PK_USUARIO_CLIENTE PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
CPF VARCHAR(20) NOT NULL,
SEXO VARCHAR(10) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
LOGIN VARCHAR(100) NOT NULL,
SENHA VARCHAR(100) NOT NULL,
DT_NASCIMENTO VARCHAR(100) NOT NULL,
END_RUA VARCHAR(50) NOT NULL,
END_NUM BIGINT NOT NULL,
END_COMPLEMENTO VARCHAR(50),
END_BAIRRO VARCHAR(50) NOT NULL,
END_CEP VARCHAR(50) NOT NULL,
END_CIDADE VARCHAR(50) NOT NULL,
END_ESTADO VARCHAR(50) NOT NULL
);*/

CREATE TABLE USUARIO(
ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) CONSTRAINT PK_USUARIO_CLIENTE PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
CPF VARCHAR(20) NOT NULL,
PAPEL VARCHAR(50) NOT NULL,
SEXO VARCHAR(10) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
LOGIN VARCHAR(100) NOT NULL,
SENHA VARCHAR(100) NOT NULL,
DT_NASCIMENTO VARCHAR(100) NOT NULL,
END_RUA VARCHAR(50) NOT NULL,
END_NUM BIGINT NOT NULL,
END_COMPLEMENTO VARCHAR(50),
END_BAIRRO VARCHAR(50) NOT NULL,
END_CEP VARCHAR(50) NOT NULL,
END_CIDADE VARCHAR(50) NOT NULL,
END_ESTADO VARCHAR(50) NOT NULL
);


--CREATE TABLE USUARIO_ADMIN(
--ID_ADMIN BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) CONSTRAINT PK_USUARIO_ADMIN PRIMARY KEY,
--NOME VARCHAR(100) NOT NULL,
--EMAIL VARCHAR(100) NOT NULL,
--LOGIN VARCHAR(100) NOT NULL,
--SENHA VARCHAR(100) NOT NULL
--);


/*CREATE TABLE CARRINHO
(
ID_CARRINHO BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) CONSTRAINT PK_CARRINHO PRIMARY KEY,
ID_CLIENTE BIGINT NOT NULL,
DAT0A_PEDIDO DATE NOT NULL,
VALOR_TOTAL DOUBLE NOT NULL,
--IS_CONCLUIDO BOOLEAN NOT NULL,--
FORMAPAGT VARCHAR(100) NOT NULL
);

CREATE TABLE ITENS_CARRINHO(
ID_CARRINHO BIGINT NOT NULL,
ID_PRODUTO BIGINT NOT NULL,
QTD INTEGER
);

ALTER TABLE ITENS_CARRINHO ADD CONSTRAINT FK_ITENS_CARRINHO FOREIGN KEY (ID_CARRINHO) REFERENCES CARRINHO(ID_CARRINHO);
ALTER TABLE ITENS_CARRINHO ADD CONSTRAINT FK_ITENS_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES TB_PRODUTO(ID_PRODUTO);

CREATE TABLE CONTROLE_PRODUTO(
ID_CONTROLE BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) CONSTRAINT PK_CONTROLE_PRODUTO PRIMARY KEY,
ID_PRODUTO BIGINT,
TAMANHO VARCHAR(100) NOT NULL,
COR VARCHAR(100) NOT NULL,
QUANTIDADE INTEGER NOT NULL
);*/


CREATE TABLE TB_VENDA(
ID_VENDA BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 10000, INCREMENT BY 1) CONSTRAINT PK_VENDA PRIMARY KEY,
NM_CLIENTE VARCHAR(100) NOT NULL,
DT_VENDA TIMESTAMP NOT NULL,
VL_TOTAL DOUBLE NOT NULL

);
--ALTER TABLE TB_VENDA ADD CONSTRAINT FK_VENDA_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES USUARIO(ID);

CREATE TABLE ITENS_VENDA(
ID_ITENS BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) CONSTRAINT PK_ITENS PRIMARY KEY,
ID_PRODUTO BIGINT NOT NULL,
ID_VENDA BIGINT NOT NULL
);
ALTER TABLE ITENS_VENDA ADD CONSTRAINT FK_ITENS_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES TB_PRODUTO(ID_PRODUTO);
ALTER TABLE ITENS_VENDA ADD CONSTRAINT FK_ITENS_VENDA FOREIGN KEY (ID_VENDA) REFERENCES TB_VENDA(ID_VENDA);




