--Alterado
CREATE TABLE TB_PRODUTO (
ID_PRODUTO BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) CONSTRAINT PK_PRODUTO PRIMARY KEY, 
NM_PRODUTO VARCHAR(100) NOT NULL,
ID_MARCA BIGINT NOT NULL,
GN_PRODUTO VARCHAR(100) NOT NULL,
DS_PRODUTO VARCHAR(1000) NOT NULL,
TM_PRODUTO VARCHAR(50) NOT NULL,
COR_PRODUTO VARCHAR(50) NOT NULL,
DT_CADASTRO TIMESTAMP NOT NULL,
VL_PRODUTO DECIMAL(12,2) NOT NULL,
QTD_ATUAL INTEGER NOT NULL,
ID_CATEGORIA BIGINT NOT NULL
);

ALTER TABLE TB_PRODUTO ADD CONSTRAINT FK_PRODUTO_MARCA FOREIGN KEY (ID_MARCA) REFERENCES TB_MARCA(ID_MARCA);
ALTER TABLE TB_PRODUTO ADD CONSTRAINT FK_PRODUTO_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES TB_CATEGORIA(ID_CATEGORIA);

--Alterado
CREATE TABLE TB_MARCA(
ID_MARCA BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) CONSTRAINT PK_MARCA PRIMARY KEY,
NOME_MARCA VARCHAR(100) NOT NULL
);

CREATE TABLE TB_IMAGEM (
ID_IMAGEM BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) CONSTRAINT PK_IMAGEM PRIMARY KEY,
NM_IMAGEM VARCHAR(100) NOT NULL,
DS_IMAGEM VARCHAR(100),
ID_PRODUTO BIGINT NOT NULL
);

ALTER TABLE TB_IMAGEM ADD CONSTRAINT FK_PRODUTO_IMAGEM FOREIGN KEY (ID_PRODUTO) REFERENCES TB_PRODUTO(ID_PRODUTO);

CREATE TABLE TB_CATEGORIA (
ID_CATEGORIA BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) CONSTRAINT PK_CATEGORIA PRIMARY KEY,
NM_CATEGORIA VARCHAR(100) NOT NULL
);

CREATE TABLE TB_PRODUTO_CATEGORIA (
ID_PRODUTO BIGINT NOT NULL,
ID_CATEGORIA INT NOT NULL
);

ALTER TABLE TB_PRODUTO_CATEGORIA ADD CONSTRAINT FK_PRODUTO_CATEGORIA FOREIGN KEY (ID_PRODUTO) REFERENCES TB_PRODUTO(ID_PRODUTO);

ALTER TABLE TB_PRODUTO_CATEGORIA ADD CONSTRAINT FK_CATEGORIA_PRODUTO FOREIGN KEY (ID_CATEGORIA) REFERENCES TB_CATEGORIA(ID_CATEGORIA);

--ACRESCENTADO
CREATE TABLE USUARIO_CLIENTE(
ID_CLIENTE BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) CONSTRAINT PK_USUARIO_CLIENTE PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
CPF VARCHAR(11) NOT NULL,
SEXO VARCHAR(10) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
LOGIN VARCHAR(100) NOT NULL,
SENHA VARCHAR(100) NOT NULL,
ENDERECO VARCHAR(100) NOT NULL

);


CREATE TABLE USUARIO_ADMIN(
ID_ADMIN BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) CONSTRAINT PK_USUARIO_ADMIN PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
LOGIN VARCHAR(100) NOT NULL,
SENHA VARCHAR(100) NOT NULL

);


CREATE TABLE CARRINHO
(
ID_CARRINHO BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) CONSTRAINT PK_CARRINHO PRIMARY KEY,
ID_CLIENTE BIGINT NOT NULL,
DATA_PEDIDO DATE NOT NULL,
VALOR_TOTAL DOUBLE NOT NULL,
IS_CONCLUIDO BOOLEAN NOT NULL,
FORMAPAGT VARCHAR(100) NOT NULL
);

CREATE TABLE ITENS_CARRINHO(
ID_CARRINHO BIGINT NOT NULL,
ID_PRODUTO BIGINT NOT NULL,
QTD INTEGER
);
ALTER TABLE ITENS_CARRINHO_CARRINHO ADD CONSTRAINT FK_ITENS_CARRINHO FOREIGN KEY (ID_CARRINHO) REFERENCES TB_CARRINHO(ID_CARRINHO);
ALTER TABLE ITENS_PRODUTO ADD CONSTRAINT FK_ITENS_CARRINHO FOREIGN KEY (ID_PRODUTO) REFERENCES TB_PRODUTO(ID_PRODUTO);

CREATE TABLE CONTROLE_PRODUTO(
ID_CONTROLE BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) CONSTRAINT PK_CONTROLE_PRODUTO PRIMARY KEY,
ID_PRODUTO BIGINT,
TAMANHO VARCHAR(100) NOT NULL,
COR VARCHAR(100) NOT NULL,
QUANTIDADE INTEGER NOT NULL
);